[package]
name = "dmg"
version = "0.1.0"
authors = ["Justin Sacbibit <jsacbibit@gmail.com>"]

[profile.dev]
debug-assertions = false
[profile.test]
debug-assertions = false

[dependencies]
glium = "*"
